import { ClientType } from "./clientType"

export const MARITIME: ClientType[] = [
    { name: "maritime", logoLocation: "/clients/maritime/maritime-01.png", type: "maritime", width: 1280, height: 796 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-02.png", type: "maritime", width: 1600, height: 1000 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-03.png", type: "maritime", width: 1065, height: 1065 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-04.png", type: "maritime", width: 1280, height: 1187 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-05.png", type: "maritime", width: 298, height: 115 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-06.png", type: "maritime", width: 960, height: 1281 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-07.png", type: "maritime", width: 1280, height: 640 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-08.png", type: "maritime", width: 2020, height: 382 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-09.png", type: "maritime", width: 320, height: 320 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-10.png", type: "maritime", width: 700, height: 565 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-11.png", type: "maritime", width: 200, height: 200 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-12.png", type: "maritime", width: 2379, height: 471 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-13.png", type: "maritime", width: 1262, height: 203 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-14.png", type: "maritime", width: 576, height: 432 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-15.png", type: "maritime", width: 200, height: 204 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-16.png", type: "maritime", width: 333, height: 160 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-17.png", type: "maritime", width: 750, height: 529 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-18.png", type: "maritime", width: 462, height: 462 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-19.png", type: "maritime", width: 462, height: 462 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-20.png", type: "maritime", width: 225, height: 163 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-21.png", type: "maritime", width: 235, height: 154 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-22.png", type: "maritime", width: 960, height: 450 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-23.png", type: "maritime", width: 500, height: 500 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-24.png", type: "maritime", width: 2363, height: 258 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-25.png", type: "maritime", width: 456, height: 220 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-26.png", type: "maritime", width: 960, height: 298 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-27.png", type: "maritime", width: 200, height: 200 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-28.png", type: "maritime", width: 1402, height: 854 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-29.png", type: "maritime", width: 4778, height: 1198 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-30.png", type: "maritime", width: 4267, height: 896 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-31.png", type: "maritime", width: 708, height: 708 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-32.png", type: "maritime", width: 1600, height: 1006 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-33.png", type: "maritime", width: 959, height: 233 },
    { name: "maritime", logoLocation: "/clients/maritime/maritime-34.png", type: "maritime", width: 288, height: 93 },
]
